### ISSUE TITLE
No access if password contains special-chars like '@'

### ISSUE THREAD

**Issue by dknacke** [rylarson/chef-artifactory_rest#3]
As soon as username and password needed a source-uri will be created as String to deliver in remote_file action, but it fails when password has special chars like '@'. I guess escaping chars isn't possible. But maybe credentials via headers should work.

eg. like:

> headers( "Authorization"=>"Basic #{ Base64.encode64("#{username}:#{password}").gsub("\n", "") }" )
> https://docs.chef.io/resource_remote_file.html

**Comment by rylarson** [comment]
Can you post a stacktrace? I think this is probably a bug in the underlying [Artifactory Client](https://github.com/chef/artifactory-client) gem

**Comment by dknacke** [comment]
take a look here:

stacktrace:

```
Generated at 2016-05-09 15:32:45 +0000
Chef::Exceptions::EnclosingDirectoryDoesNotExist: group: commons-io, artifact id: commons-io, version: 1.*, classifier: , packaging: jar, repository_keys: ["central-maven-remote-cache"] (MyCookbookTest::default line 9) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: remote_file[Downloading file https://dknacke:p@ssword%123@artifactory.server.com:443/artifactory/central-maven-remote-cache/commons-io/commons-io/1.4/commons-io-1.4.jar specified by: group: commons-io, artifact id: commons-io, version: 1.*, classifier: , packaging: jar, repository_keys: ["central-maven-remote-cache"]] (/tmp/kitchen/cookbooks/artifactory_rest/providers/gavc_download.rb line 25) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /tmp/downloads does not exist.
[...]
```

within my cookbook recipe-default:

```
include_recipe 'artifactory_rest' 

artifactory_rest_gavc_download '/tmp/downloads/commons-io.jar' do
  username 'dknacke'
  password 'p@ssword%123'
  group_id 'commons-io'
  artifact_id 'commons-io'
  endpoint 'https://artifactory.server.com/artifactory'
  version '1.*'
  repository_keys ['central-maven-remote-cache']
  packaging 'jar'
end
```

**Comment by rylarson** [comment]
This looks like it is complaining that `/tmp/downloads` does not exist yet.

Can you add

```
directory '/tmp/downloads' do
  action :create
  recursive = true
end
```

At the top of your recipe to make sure the directory exists?

**Comment by dknacke** [comment]
oh yes. I'm sorry. Check this:

```
Generated at 2016-05-09 16:27:35 +0000
Chef::Exceptions::InvalidRemoteFileURI: group: commons-io, artifact id: commons-io, version: 2.*, classifier: , packaging: jar, repository_keys: ["central-maven-remote-cache"] (MyCookbookTest::default line 14) had an error: Chef::Exceptions::InvalidRemoteFileURI: "https://dknacke:p@ssword%123@artifactory.server.com:443/artifactory/central-maven-remote-cache/commons-io/commons-io/2.4/commons-io-2.4.jar" is not a valid `source` parameter for remote_file. `source` must be an absolute URI or an array of URIs.
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource/remote_file.rb:143:in `block in validate_source'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource/remote_file.rb:141:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource/remote_file.rb:141:in `validate_source'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/params_validate.rb:317:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/params_validate.rb:317:in `block in _pv_callbacks'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/params_validate.rb:316:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/params_validate.rb:316:in `_pv_callbacks'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/params_validate.rb:106:in `block (2 levels) in validate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/params_validate.rb:103:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/params_validate.rb:103:in `block in validate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/params_validate.rb:93:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/params_validate.rb:93:in `validate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/property.rb:467:in `validate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/property.rb:653:in `coerce_and_validate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/property.rb:632:in `input_to_stored_value'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/property.rb:389:in `set'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/property.rb:288:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/params_validate.rb:483:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/params_validate.rb:122:in `set_or_return'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource/remote_file.rb:51:in `source'
/tmp/kitchen/cookbooks/artifactory_rest/providers/gavc_download.rb:26:in `block (3 levels) in class_from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_builder.rb:76:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_builder.rb:76:in `build'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/dsl/declare_resource.rb:102:in `build_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/dsl/declare_resource.rb:62:in `declare_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/dsl/resources.rb:40:in `remote_file'
/tmp/kitchen/cookbooks/artifactory_rest/providers/gavc_download.rb:25:in `block (2 levels) in class_from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/provider.rb:175:in `converge_by'
/tmp/kitchen/cookbooks/artifactory_rest/providers/gavc_download.rb:23:in `block in class_from_file'
(eval):2:in `block in action_download'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/provider.rb:360:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/provider.rb:360:in `compile_and_converge_action'
(eval):2:in `action_download'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/provider.rb:144:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource.rb:596:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_collection/resource_list.rb:84:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_collection/resource_list.rb:82:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/client.rb:667:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/client.rb:662:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/client.rb:662:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/client.rb:701:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application.rb:285:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application.rb:273:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application.rb:273:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application.rb:238:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application.rb:226:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application/solo.rb:301:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application/solo.rb:290:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application/solo.rb:290:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application/solo.rb:269:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/bin/chef-solo:25:in `<top (required)>'
```

recipe-default was:

```
include_recipe 'artifactory_rest' 

directory '/tmp/downloads' do
  action :create
  recursive = true
end

artifactory_rest_gavc_download '/tmp/downloads/commons-io.jar' do
  username 'dknacke'
  password 'p@ssword%123'
  group_id 'commons-io'
  artifact_id 'commons-io'
  endpoint 'https://artifactory.server.com/artifactory'
  version '2.*'
  repository_keys ['central-maven-remote-cache']
  packaging 'jar'
end
```

**Comment by dknacke** [comment]
As soon as my password has no '@' it works fine.

**Comment by rylarson** [comment]
Ah ok, I see what is happening. We are just not URL escaping the user/password fields.

I can get this fixed pretty quickly. In the mean time, you can use CGI directly to escape your password:

```
directory '/tmp/downloads' do
  action :create
  recursive = true
end

require 'cgi'

artifactory_rest_gavc_download '/tmp/downloads/commons-io.jar' do
  username 'dknacke'
  password CGI.escape('p@ssword%123')
  group_id 'commons-io'
  artifact_id 'commons-io'
  endpoint 'https://artifactory.server.com/artifactory'
  version '2.*'
  repository_keys ['central-maven-remote-cache']
  packaging 'jar'
end
```

**Comment by dknacke** [comment]
Thank you!

Within gavc_download.rb, could be this a solution as well ?

```
use_inline_resources

def whyrun_supported?
  true
end

action :download do
  if new_resource.classifier.to_s.empty? then
    new_resource.classifier = nil
  end
  downloader = ArtifactoryDownloader.new(endpoint: new_resource.endpoint, username: new_resource.username, password: new_resource.password)
  download_uri = downloader.resolve_download_uri(group: new_resource.group_id,
                                                 artifact: new_resource.artifact_id,
                                                 version: new_resource.version,
                                                 classifier: new_resource.classifier,
                                                 repos: new_resource.repository_keys,
                                                 packaging: new_resource.packaging)

  resource_name = "Downloading file #{download_uri} specified by: #{new_resource.to_s}"
  converge_by(resource_name) do
    # Delegate to remote_file for idempotency
    remote_file resource_name do
      if new_resource.username && new_resource.password then
        headers "Authorization" => "Basic #{::Base64.encode64("#{new_resource.username}:#{new_resource.password}").chomp}"    
      end
      source download_uri
      path new_resource.path
    end
  end
end
```
